export type ApplicationErrorCode =
  | "BOOKING_DATE_TOO_FAR_IN_FUTURE"
  | "BOOKING_EXPERIENCE_NOT_BOOKABLE"
  | "BOOKING_EXTRA_MINIMUM_NOTICE_NOT_MET"
  | "BOOKING_EXTRA_NOT_COMPATIBLE"
  | "BOOKING_EXTRA_QUANTITY_NOT_ALLOWED"
  | "BOOKING_GUEST_CAPACITY_EXCEEDED"
  | "BOOKING_MINIMUM_NOTICE_NOT_MET"
  | "BOOKING_ALREADY_CANCELLED"
  | "BOOKING_ACCESS_EXPIRED"
  | "BOOKING_ACCESS_INVALID"
  | "BOOKING_NOT_EDITABLE"
  | "BOOKING_NOT_FOUND"
  | "BOOKING_PAYMENT_NOT_PENDING"
  | "BOOKING_PAYMENT_PROVIDER_MISMATCH"
  | "BOOKING_PAYMENT_SESSION_MISSING"
  | "BOOKING_PAYMENT_SESSION_NOT_FOUND"
  | "BOOKING_SELECTED_SLOT_OUTSIDE_POLICY"
  | "CALENDAR_BLOCK_NOT_FOUND"
  | "CALENDAR_BLOCK_OVERLAP"
  | "CALENDAR_DATE_RANGE_INVALID"
  | "COUPON_ALREADY_EXISTS"
  | "COUPON_CODE_REQUIRED"
  | "COUPON_CURRENCY_MISMATCH"
  | "COUPON_EXPERIENCE_NOT_ALLOWED"
  | "COUPON_EXPIRED"
  | "COUPON_INACTIVE"
  | "COUPON_LIMIT_REACHED"
  | "COUPON_NOT_FOUND"
  | "COUPON_NOT_STARTED"
  | "COUPON_RULE_INVALID"
  | "EXPERIENCE_ALREADY_EXISTS"
  | "EXPERIENCE_ID_MISSING"
  | "EXPERIENCE_NOT_FOUND"
  | "EXTRA_ALREADY_EXISTS"
  | "EXTRA_NOT_FOUND"
  | "HOME_GALLERY_NOT_ENOUGH_READY_ASSETS"
  | "MEDIA_ASSET_ALREADY_EXISTS"
  | "MEDIA_ASSET_NOT_FOUND"
  | "MEDIA_PROCESSING_JOB_NOT_FOUND"
  | "NOTIFICATION_DELIVERY_ALREADY_FINALIZED"
  | "NOTIFICATION_DELIVERY_NOT_FOUND"
  | "NOTIFICATION_OUTBOX_EVENT_UNSUPPORTED"
  | "NOTIFICATION_OUTBOX_MESSAGE_NOT_FOUND"
  | "NOTIFICATION_PREVIEW_FIXTURE_MISSING"
  | "NOTIFICATION_PREVIEW_SOURCE_MISSING"
  | "NOTIFICATION_PROCESSING_FAILED"
  | "NOTIFICATION_PROVIDER_FAILED"
  | "NOTIFICATION_RULE_CANNOT_ENABLE"
  | "NOTIFICATION_RULE_DUPLICATE"
  | "NOTIFICATION_RULE_NOT_FOUND"
  | "NOTIFICATION_TEMPLATE_NOT_FOUND"
  | "NOTIFICATION_TEMPLATE_TRANSLATION_MISSING";

export class ApplicationError extends Error {
  readonly code: ApplicationErrorCode;

  constructor(code: ApplicationErrorCode, message: string) {
    super(message);
    this.name = "ApplicationError";
    this.code = code;
  }
}

export function applicationError(code: ApplicationErrorCode, message: string) {
  return new ApplicationError(code, message);
}
