export type DomainErrorCode =
  | "EXPERIENCE_ARCHIVED"
  | "EXPERIENCE_BUFFER_INVALID"
  | "EXPERIENCE_CAPACITY_INVALID"
  | "EXPERIENCE_DEPARTURE_PORT_MISSING"
  | "EXPERIENCE_DISPLAY_ORDER_INVALID"
  | "EXPERIENCE_DURATION_INVALID"
  | "EXPERIENCE_EXTRA_NOT_COMPATIBLE"
  | "EXPERIENCE_ID_MISSING"
  | "EXPERIENCE_MAXIMUM_ADVANCE_INVALID"
  | "EXPERIENCE_MINIMUM_ADVANCE_INVALID"
  | "EXPERIENCE_NAME_MISSING"
  | "EXPERIENCE_NOT_PUBLISHABLE"
  | "EXPERIENCE_PRICE_MISSING"
  | "EXPERIENCE_PRIMARY_IMAGE_MISSING"
  | "EXPERIENCE_PRIMARY_IMAGE_NOT_READY"
  | "EXPERIENCE_SLOT_POLICY_INVALID"
  | "EXTRA_CAPACITY_REDUCTION_INVALID"
  | "EXTRA_ID_MISSING"
  | "EXTRA_MINIMUM_NOTICE_INVALID"
  | "EXTRA_NAME_MISSING"
  | "EXTRA_NOT_SELECTABLE"
  | "EXTRA_PRICE_MISSING"
  | "EXTRA_QUANTITY_NOT_ALLOWED"
  | "LOCALE_CODE_MISSING"
  | "LOCALE_CODE_UNSUPPORTED"
  | "LOCALIZED_CONTENT_NOT_PUBLISHABLE"
  | "MONEY_AMOUNT_INVALID"
  | "MONEY_CURRENCY_INVALID"
  | "SLUG_INVALID"
  | "SLUG_MISSING"
  | "SLOT_POLICY_INVALID"
  | "TIME_RANGE_INVALID";

export class DomainError extends Error {
  readonly code: DomainErrorCode;

  constructor(code: DomainErrorCode, message: string) {
    super(message);
    this.name = "DomainError";
    this.code = code;
  }
}

export function domainError(code: DomainErrorCode, message: string) {
  return new DomainError(code, message);
}
